name: Lint GitHub Actions workflows

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow files

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Download actionlint
        id: download_actionlint
        run: |
          bash <(curl "https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash")

      - name: Lint workflow files with actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          ${{ steps.download_actionlint.outputs.executable }} -color
